# Generated by Django 5.1.5 on 2025-02-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='processed_images/')),
                ('alt_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docprocessor.docfile')),
            ],
        ),
    ]
